version: "3.13"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: agenda_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: gunicorn --config gunicorn/gunicorn.conf.py project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - web

volumes:
  mysql_data: